services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    # volumes:
    #   - ./:/app # bind mount for dev
    #   - /app/node_modules # preserve node modules
    depends_on:
      - redis
      - db

  redis:
    image: redis:8.2-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # db volume
      - ./src/db/sql:/docker-entrypoint-initdb.d # db schemas and seeding

volumes:
  redis_data:
  postgres_data:
